version: '3'

services:
  minecraft:
    ports:
      - '25565:25565'

    environment:
      EULA: 'TRUE'
      TYPE: 'CURSEFORGE'
      FTB_SERVER_MOD: 'https://minecraft.curseforge.com/projects/sevtech-ages/files/2570735/download'

    image: itzg/minecraft-server

    container_name: mc

    tty: true
    stdin_open: true
    restart: always
