apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sevtech-pvc-storage
  namespace: sevtech
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sevtech-pv-storage
